# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['Linux', 'FreeBSD', 'Windows']
   'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kcontacts': '@latest-kf6'
    'frameworks/kcalendarcore': '@latest-kf6'
    'frameworks/kwallet': '@latest-kf6'

Options:
 require-passing-tests-on: ['Linux', 'FreeBSD']
 allow-failing-tests-on: ['Windows']
